# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

install! 'cocoapods', :deterministic_uuids => false

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
# use_frameworks!

rn_path = '../node_modules/react-native'

pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
pod 'React', path: rn_path, subspecs: [
  'ART',
  'Core',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
]

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

target 'soundCheck' do
  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end